spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btg
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver_class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
